# Generated by Django 3.2 on 2022-05-05 09:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('filename', models.CharField(max_length=250)),
                ('kind', models.PositiveSmallIntegerField(choices=[(1, 'Profile Picture'), (2, 'Excel Report'), (3, 'Resume')], default=1)),
                ('mimetype', models.CharField(max_length=100)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Uploading'), (2, 'Uploaded'), (3, 'Processing'), (4, 'Processed'), (5, 'Error')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='core.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
